project:
  type: book
  output-dir: docs

execute:
  warning: false
  echo: true

book:
  title: "Where it pays to attend College"
  author:
    - Harinder Singh Mashiana (hm3008)
    - Jahnavi Mulchandani (jm5667)
  repo-url: https://github.com/harindermashiana/collegeSalaries.git
  date: 11-29-2023
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  options:
    warning: FALSE
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


